import React from 'react';

export default function TermsOfService() {
  return (
    <div style={{ padding: '2rem', maxWidth: '900px', margin: '0 auto', color: '#e0e0e0' }}>
      <h1 style={{ color: '#72ffaf' }}>Terms of Service</h1>
      <p><strong>Effective Date:</strong> May 24, 2025</p>

      <p>
        Welcome to HelpLineAI. These Terms of Service ("Terms") govern your access to and use of the HelpLineAI platform,
        website, applications, and services ("Service"). By accessing or using the Service, you agree to be legally bound
        by these Terms. If you do not agree to these Terms, you may not use the Service.
      </p>

      <h2>1. No Medical or Professional Advice</h2>
      <p>
        HelpLineAI is an AI-powered mental health support assistant. The content generated by the Service is for
        informational and educational purposes only and is not intended as a substitute for professional medical advice,
        diagnosis, or treatment. Always seek the advice of a qualified healthcare provider with any questions you may have
        regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of
        something you read or received via HelpLineAI.
      </p>

      <h2>2. Emergency and Crisis Use Prohibited</h2>
      <p>
        The Service is not intended for use in emergencies. If you or someone you know is experiencing a medical emergency,
        crisis, or thoughts of self-harm or suicide, you must call 911 (in the U.S.) or the appropriate emergency services
        in your region. The Service is not monitored 24/7 and cannot respond to urgent requests for help.
      </p>

      <h2>3. Regional Crisis Support</h2>
      <p>
        In situations where the system detects high-risk or crisis language (e.g., self-harm or suicide references), the
        Service will provide contact information for appropriate crisis lines and regional support. These numbers are
        provided for informational purposes only.
      </p>

      <h2>4. Data Privacy & Security</h2>
      <p>
        We are committed to protecting your privacy. All chats are anonymized and stored with end-to-end encryption
        using industry best practices. We do not sell, share, or distribute identifiable user data. The Service complies
        with applicable data privacy regulations including the Health Insurance Portability and Accountability Act (HIPAA),
        General Data Protection Regulation (GDPR), and any relevant national laws.
      </p>
      <ul>
        <li>Minimal metadata (e.g., account ID, timestamps) may be stored to enable basic functionality.</li>
        <li>You may request full deletion of your account and associated data at any time.</li>
        <li>We log certain actions (e.g., emergency resource delivery) securely for compliance auditing.</li>
      </ul>

      <h2>5. Permitted Use and User Responsibilities</h2>
      <p>
        You agree to use the Service solely for lawful and supportive purposes. You may not:
      </p>
      <ul>
        <li>Use the Service to promote hate speech, misinformation, or illegal activity.</li>
        <li>Exploit or attempt to reverse-engineer the AI system or its underlying infrastructure.</li>
        <li>Impersonate another individual or misrepresent your identity.</li>
      </ul>
      <p>
        HelpLineAI reserves the right to terminate access to users who violate these rules, with or without prior notice.
      </p>

      <h2>6. Eligibility</h2>
      <p>
        You must be at least 13 years of age to use the Service. If you are under 18, you must have permission from a
        parent or legal guardian. The Service is not intended for users in jurisdictions where its content or functionality
        is illegal or restricted.
      </p>

      <h2>7. Google Authentication and Account Creation</h2>
      <p>
        You may log in or register using third-party providers such as Google. By doing so, you agree to allow us to access
        your public profile information (such as email and name) for the sole purpose of creating and managing your account.
        You remain responsible for maintaining the confidentiality of your login credentials.
      </p>

      <h2>8. Intellectual Property</h2>
      <p>
        All content, branding, and materials on HelpLineAI, including but not limited to logos, UI elements, code,
        text, and AI-generated responses, are the intellectual property of HelpLineAI or its licensors and may not
        be copied, distributed, or modified without explicit permission.
      </p>

      <h2>9. Service Modifications and Termination</h2>
      <p>
        We reserve the right to modify, suspend, or terminate the Service or your access to it at any time, with or without
        cause or notice. This includes routine maintenance, upgrades, or security-related shutdowns.
      </p>

      <h2>10. Changes to Terms</h2>
      <p>
        We may update these Terms periodically. If you have an account, we will prompt you to re-accept the updated Terms
        upon your next login. Continued use of the Service after any changes constitutes acceptance of the revised Terms.
      </p>

      <h2>11. Disclaimers and Limitation of Liability</h2>
      <p>
        The Service is provided "as is" and "as available" without warranties of any kind. We do not guarantee that the
        Service will be uninterrupted, error-free, or always accurate. HelpLineAI and its affiliates, partners, developers,
        and agents shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from
        your use of the Service.
      </p>

      <h2>12. Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the laws of the United States and the State of
        Delaware, without regard to its conflict of law provisions.
      </p>

      <p style={{ marginTop: '2rem' }}>
        By using this service or clicking "I Accept", you confirm that you have read, understood, and agreed to these
        Terms of Service in full. If you do not agree, you must discontinue use immediately.
      </p>
    </div>
  );
}
